name: Build ASAZU Studio APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Fix Flutter project structure
        run: |
          mkdir -p lib test

          for f in *.dart; do
            if [[ "$f" != *_test.dart ]]; then
              mv "$f" lib/
            fi
          done

          for f in *_test.dart; do
            if [ -f "$f" ]; then
              mv "$f" test/
            fi
          done

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos

      - name: Test
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: ASAZU-STUDIO-APK
          path: build/app/outputs/flutter-apk/app-release.apk
